repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-merge-conflict
        -   id: check-symlinks
        -   id: mixed-line-ending
            args: ['--fix=lf']
        -   id: check-added-large-files
            args: ['--maxkb=8192']
        -   id: fix-byte-order-marker
        -   id: fix-encoding-pragma
            args: ['--remove']
        #-   id: no-commit-to-branch
        #    args: [--branch, master]
    -   repo: https://github.com/doublify/pre-commit-rust
        rev: v1.0
        hooks:
        -   id: fmt
        -   id: clippy
