[package]
name = "bqskitrs"
version = "0.1.0-alpha.2"
authors = ["Ethan Smith <ethanhs@berkeley.edu>"]
license = "LGPL-2.1 AND BSD-3-Clause"
edition = "2018"
build = "build.rs"
publish = false
include = [
    "src/**/*",
    "LICENSE",
    "README.md",
    "build.rs",
    "Dockerfile",
    "pyproject.toml",
    "squaremat/**/*",
    "ceres/**/*",
]

[features]
static = [
    "openblas-src",
    "blas-src/openblas",
    "openblas-src/static",
    "openblas-src/cblas",
    "openblas-src/lapacke",
    "squaremat/openblas-static",
    "ceres/static",
]
default = [
    "openblas-src",
    "blas-src/openblas",
    "openblas-src/system",
    "openblas-src/cblas",
    "openblas-src/lapacke",
    "squaremat/openblas-system",
]
accelerate = ["accelerate-src", "blas-src/accelerate", "squaremat/accelerate"]
mkl = ["intel-mkl-src", "blas-src/intel-mkl", "squaremat/mkl"]

[dependencies]
num-complex = { version="0.4", features=["serde"] }
ndarray = { version="0.15", features=["blas"] }
blas-src = { version="0.8", default-features=false }
openblas-src = { version="0.10", default-features=false, optional=true }
accelerate-src = { version="0.3", optional=true }
intel-mkl-src = { version="0.5", optional=true }
enum_dispatch = "0.3"
numpy = { version="0.13.2" }
libc = "0.2"
num-traits = "0.2"
better-panic = "0.2"
squaremat = { path="./squaremat" }
md5 = "0.7"
rand = "0.8"
nlopt = { version="0.5" }
ceres = { path="./ceres" }
itertools = "0.10"
pyo3 = { version="0.13.2", features=["extension-module", "abi3-py37"] }
lax = { git = "https://github.com/rust-ndarray/ndarray-linalg.git", rev = "c7f22aea" }
derive_more = "0.99.14"

[patch.crates-io]
openblas-src = { git = "https://github.com/blas-lapack-rs/openblas-src" }

[target.'cfg(target_os = "windows")'.build-dependencies]
vcpkg = "0.2.13"

[lib]
name = "bqskitrs"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
debug = true

[package.metadata.maturin]
classifier = [
    'Programming Language :: Python',
    'Programming Language :: Rust',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Science/Research',
    'Topic :: Software Development :: Compilers',
    'Topic :: Scientific/Engineering :: Physics',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX :: Linux',
    'Operating System :: MacOS',
]

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "2021.05.12"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet="x64-windows-static-md", install=[
    "ceres",
    "eigen3",
    "openblas",
    "glog",
    "gflags",
    "clapack",
] }
