[build-system]
requires = [
    "maturin>=0.10,<0.11",
    "wheel",
    "oldest-supported-numpy",
]
build-backend = "maturin"

[project]
name = "bqskitrs"
version = "0.2.0.rc2"
maintainers = [
    {name = "Ethan Smith", email = "ethanhs@lbl.gov"},
    {name = "Ed Younis", email = "edyounis@lbl.gov"},
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
Source = "https://github.com/bqskit/bqskitrs"

[tool.maturin]
manylinux = "off"
bindings = "pyo3"
# To use Apple's Accelerate framework, uncomment the following line
#cargo-extra-args = "--no-default-features --features=python,accelerate,ceres/static,mimalloc/local_dynamic_tls"
# To use Intel's MKL, uncomment the following line
#cargo-extra-args = "--no-default-features --features=python,mkl,mimalloc/local_dynamic_tls"
# On Windows we statically link to ceres and other dependencies
#cargo-extra-args="--no-default-features --features=python,static,mimalloc/local_dynamic_tls"
